
-- luacheck: globals GetLocale C_AddOns

if (GetLocale() == "deDE") then
  rggm = rggm or {}
  rggm.L = {}

  rggm.L["addon_name"] = "GearMenu"

  -- console
  rggm.L["help"] = "|cFFFFC300(%s)|r: Benutze |cFFFFC300/rggm|r oder |cFFFFC300/gearmenu|r "
    .. "für eine Liste der verfügbaren Optionen"
  rggm.L["opt"] = "|cFFFFC300opt|r - zeige Optionsmenu an"
  rggm.L["reload"] = "|cFFFFC300reload|r - UI neu laden"
  rggm.L["info_title"] = "|cFF00FFB0GearMenu:|r"
  rggm.L["invalid_argument"] = "Ungültiges Argument übergeben"
  rggm.L["update_available"] = "Neue Version |cFFFFC300%s|r ist verfügbar - |cFF00FFB0Update empfohlen!|r"

  -- about tab
  rggm.L["author"] = "Autor: Michael Wiesendanger"
  rggm.L["email"] = "E-Mail: michael.wiesendanger@gmail.com"
  rggm.L["version"] = "Version: " .. C_AddOns.GetAddOnMetadata(RGGM_CONSTANTS.ADDON_NAME, "Version")
  rggm.L["issues"] = "Probleme: https://github.com/RagedUnicorn/wow-classic-gearmenu/issues"

  -- general
  rggm.L["general_category_name"] = "Allgemein"
  rggm.L["general_title"] = "Allgemeine Konfiguration"
  rggm.L["enable_tooltips"] = "Aktiviere KurzInfo"
  rggm.L["enable_tooltips_tooltip"] = "Aktiviere Kurzinfo für markierte Items"
  rggm.L["enable_simple_tooltips"] = "Zeige Simple Kurzinfo"
  rggm.L["enable_simple_tooltips_tooltip"] = "Zeige nur den Titel des markierten Items anstatt die ganze Kurzinfo"
  rggm.L["enable_drag_and_drop"] = "Aktiviere Drag and Drop"
  rggm.L["enable_drag_and_drop_tooltip"] = "Aktiviere Drag and Drop für Items"
  rggm.L["enable_fast_press"] = "Aktiviere Schnellklick"
  rggm.L["enable_fast_press_tooltip"] = "Aktiviert Aktionen beim drücken eines Knopfs anstatt beim loslassen des Knopfs"
  rggm.L["enable_unequip_slot"] = "Aktiviere Ausrüstung ausziehen Slot"
  rggm.L["enable_unequip_slot_tooltip"] = "Aktiviert einen leeren Slot im ChangeMenu."
    .. " Dies erlaubt es einfacher items auszuziehen"
  rggm.L["enable_rune_slots"] = "Aktiviere Runenslots"
  rggm.L["enable_rune_slots_tooltip"] = "Aktiviert die Anzeige von Runenslots im GearBar"
  rggm.L["enable_fallback_to_base_item"] = "Ersatzkopie ausrüsten"
  rggm.L["enable_fallback_to_base_item_tooltip"] = "Wenn die exakt verzauberte/gravierte Kopie eines"
    .. " Gegenstands nicht in den Taschen gefunden werden kann, wird stattdessen eine einfache Kopie"
    .. " desselben Gegenstands ausgerüstet. Beim Ausrüsten einer Ersatzkopie wird eine Warnung im Chat angezeigt"
  rggm.L["filter_item_quality"] = "Filtere Gegenstandsqualität:"
  rggm.L["item_quality_poor"] = "Arm (Grau)"
  rggm.L["item_quality_common"] = "Gewöhnlich (Weiss)"
  rggm.L["item_quality_uncommon"] = "Ungewöhnlich (Grün)"
  rggm.L["item_quality_rare"] = "Selten (Blau)"
  rggm.L["item_quality_epic"] = "Episch (Violet)"
  rggm.L["item_quality_legendary"] = "Legendär (Orange)"
  rggm.L["choose_theme"] = "Wähle Theme:"
  rggm.L["theme_classic"] = "Klassisch"
  rggm.L["theme_custom"] = "Angepasst"
  rggm.L["theme_change_confirmation"] = "Dies wird dein Interface neu laden. Willst du fortfahren?"
  rggm.L["theme_change_confirmation_yes"] = "Ja"
  rggm.L["theme_change_confirmation_no"] = "Nein"

  -- quickchange
  rggm.L["quick_change_category_name"] = "Schnellwechsel"
  rggm.L["quick_change_title"] = "Schnellwechsel"
  rggm.L["quick_change_slider_title"] = "Verzögerung in Sekunde"
  rggm.L["quick_change_slider_tooltip"] = "Setzt eine Verzögerung wann eine Quickchange Regel "
    .. "angewendet werden sollte. Für Gegenstände welche einen Stärkungszauber auslösen sollte "
    .. "diese Verzögerung normalerweise der Dauer des Stärkungszaubers entsprechen."
  rggm.L["quick_change_slider_unit"] = "Sekunden"
  rggm.L["quick_change_add_rule"] = "Hinzufügen"
  rggm.L["quick_change_remove_rule"] = "Entfernen"
  rggm.L["quick_change_invalid_rule"] = "Der Gegenstand von dem gewechselt und der Gegenstand zu "
    .. "dem gewechselt werden soll, können nicht der gleiche Gegenstand sein"
  rggm.L["quick_change_unable_to_remove_rule"] = "Konnte Regel nicht entfernen - Bitte selektiere "
    .. "zuerst eine Regel welche entfernt werden soll"
  rggm.L["quick_change_unable_to_add_rule_from"] = "Konnte neue Regel nicht hinzufügen "
    .. "- Kein 'Von' Gegenstand ausgewählt"
  rggm.L["quick_change_unable_to_add_rule_to"] = "Konnte neue Regel nicht hinzufügen - Kein 'Zu' Gegenstand ausgewählt"
  rggm.L["quick_change_unable_to_add_rule_duplicate"] = "Konnte neue Regel nicht hinzufügen "
    .. "- Eine Regel für diesen Gegenstand existiert bereits"

  -- trinketMenu
  rggm.L["trinket_menu_category_name"] = "TrinketMenu"
  rggm.L["trinket_menu_title"] = "Trinket Menu Einstellungen"
  rggm.L["enable_trinket_menu"] = "Aktiviere TrinketMenu"
  rggm.L["enable_trinket_menu_tooltip"] = "Aktiviere oder deaktiviere die Anzeige des TrinketMenus"
  rggm.L["window_lock_trinket_menu"] = "Sperre TrinketMenu"
  rggm.L["window_lock_trinket_menu_tooltip"] = "Verhindert das verschieben des TrinketMenus"
  rggm.L["shoow_cooldowns_trinket_menu"] = "Zeige Abklingzeiten"
  rggm.L["shoow_cooldowns_trinket_menu_tooltip"] = "Aktiviere die Anzeige der Abklingzeiten"
  rggm.L["trinket_menu_column_amount_slider_title"] = "Spalten"
  rggm.L["trinket_menu_column_amount_slider_tooltip"] =
    "Anzahl Spalten die benutzt werden für die anzeige des TrinketMenus"
  rggm.L["trinket_menu_slot_size_slider_title"] = "Schmuckstückslot Grösse"
  rggm.L["trinket_menu_slot_size_slider_tooltip"] = "Konfiguriere die Grösse der Schmuckstückslots"

  -- slot translations
  rggm.L["slot_name_head"] = "Kopf"
  rggm.L["slot_name_neck"] = "Hals"
  rggm.L["slot_name_shoulders"] = "Schultern"
  rggm.L["slot_name_chest"] = "Brust"
  rggm.L["slot_name_waist"] = "Taille"
  rggm.L["slot_name_legs"] = "Beine"
  rggm.L["slot_name_feet"] = "Füße"
  rggm.L["slot_name_wrist"] = "Handgelenke"
  rggm.L["slot_name_hands"] = "Hände"
  rggm.L["slot_name_upper_finger"] = "Oberer Finger"
  rggm.L["slot_name_lower_finger"] = "Unterer Finger"
  rggm.L["slot_name_finger"] = "Finger"
  rggm.L["slot_name_upper_trinket"] = "Oberer Schmuck"
  rggm.L["slot_name_lower_trinket"] = "Unterer Schmuck"
  rggm.L["slot_name_trinket"] = "Schmuck"
  rggm.L["slot_name_back"] = "Rücken"
  rggm.L["slot_name_main_hand"] = "Waffenhand"
  rggm.L["slot_name_off_hand"] = "Schildhand"
  rggm.L["slot_name_ranged"] = "Distanz"
  rggm.L["slot_name_ammo"] = "Munition"

  -- gearbar
  rggm.L["gear_bar_configuration_category_name"] = "GearBar"
  rggm.L["gear_bar_configuration_panel_text"] = "GearBar Konfiguration"
  rggm.L["gear_bar_configuration_add_gearbar"] = "Erstelle neue GearBar"
  rggm.L["gear_bar_choose_name"] = "Wähle einen Namen für die neue GearBar"
  rggm.L["gear_bar_choose_name_accept_button"] = "Akzeptieren"
  rggm.L["gear_bar_choose_name_cancel_button"] = "Abbrechen"
  rggm.L["gear_bar_remove_button"] = "Entferne GearBar"
  rggm.L["gear_bar_confirm_delete"] = "Willst du diese GearBar wirklich löschen?"
  rggm.L["gear_bar_confirm_delete_yes_button"] = "Ja"
  rggm.L["gear_bar_confirm_delete_no_button"] = "Nein"
  rggm.L["gear_bar_max_amount_of_gear_bars_reached"] =
    "Du hast das maximum von " .. RGGM_CONSTANTS.MAX_GEAR_BARS .. " GearBars erreicht"

  -- gearbar options
  rggm.L["window_lock_gear_bar"] = "Sperre Ausrüstungsbalken"
  rggm.L["window_lock_gear_bar_tooltip"] = "Verhindert das bewegen des Ausrüstungsbalken"
  rggm.L["gear_bar_drag_handle_tooltip"] = "Ziehen, um den Ausrüstungsbalken zu bewegen"
  rggm.L["show_keybindings"] = "Zeige Tastaturkürzel an"
  rggm.L["show_keybindings_tooltip"] = "Zeige Tastaturkürzel auf den ausgerüsteten Items an"
  rggm.L["show_cooldowns"] = "Zeige Abklingzeiten an"
  rggm.L["show_cooldowns_tooltip"] = "Zeige Abklingzeiten für alle Slots an"
  rggm.L["gear_slot_size_slider_title"] = "Ausrüstungsslot Grösse"
  rggm.L["gear_slot_size_slider_tooltip"] = "Verändere die Grösse der Ausrüstungsslots"
  rggm.L["change_slot_size_slider_title"] = "Wechselslots Grösse"
  rggm.L["change_slot_size_slider_tooltip"] = "Verändere die Grösse der Wechselslots"
  rggm.L["gearbar_orientation"] = "Ausrichtung"
  rggm.L["gearbar_orientation_tooltip"] =
    "Wähle, ob dieser Ausrüstungsbalken seine Slots horizontal oder vertikal anordnet"
  rggm.L["orientation_horizontal"] = "Horizontal"
  rggm.L["orientation_vertical"] = "Vertikal"
  rggm.L["change_menu_direction"] = "Wechselmenü-Richtung"
  rggm.L["change_menu_direction_tooltip"] =
    "Wähle, in welche Richtung sich das Wechselmenü relativ zum Ausrüstungsslot öffnet"
  rggm.L["change_menu_direction_up"] = "Oben"
  rggm.L["change_menu_direction_down"] = "Unten"
  rggm.L["change_menu_direction_left"] = "Links"
  rggm.L["change_menu_direction_right"] = "Rechts"
  rggm.L["gear_bar_max_amount_of_gear_slots_reached"] =
    "Du hast das maximum von " .. RGGM_CONSTANTS.MAX_GEAR_BAR_SLOTS .. " GearBar Slots erreicht"
  -- add/remove slots
  rggm.L["gear_bar_configuration_add_gearslot"] = "Erstelle Gearslot"
  rggm.L["gear_bar_configuration_add_gearslot_combat"] =
    "Im Kampf kann kein Gearslot hinzugefügt werden. Bitte versuche es nach dem Kampf erneut"
  rggm.L["gear_bar_configuration_remove_gearslot"] = "-"
  rggm.L["gear_bar_configuration_delete_gearbar"] = "Lösche GearBar"
  -- gearbar scrollmenu
  rggm.L["gear_bar_configuration_key_binding_button"] = "Erstelle/Entferne Kürzel"
  rggm.L["gear_bar_configuration_key_binding_not_set"] = "Kein Kürzel gesetzt"
  rggm.L["gear_bar_configuration_key_binding_dialog"] = "Setze Tastenkürzel zu: "
  rggm.L["gear_bar_configuration_key_binding_dialog_initial"] = "(drücke das Tastenkürzel das du verwenden willst "
    .. "oder lasse es leer um das Tastenkürzel zurückzusetzen)"
  rggm.L["gear_bar_configuration_key_binding_dialog_accept"] = "Akzeptieren"
  rggm.L["gear_bar_configuration_key_binding_dialog_cancel"] = "Abbrechen"
  rggm.L["gear_bar_configuration_key_binding_override_dialog"] = "Tastenkürzel wird bereits benutzt. "
    .. "Willst du es überschreiben?"
  rggm.L["gear_bar_configuration_key_binding_dialog_override_yes"] = "Ja"
  rggm.L["gear_bar_configuration_key_binding_dialog_override_no"] = "Nein"
  rggm.L["gear_bar_configuration_key_binding_user_error"] = "Setzen des neuen Tastenkürzels ist fehlgeschlagen"

  -- macro bridge user errors
  rggm.L["unable_to_find_equipslot"] = "Konnte keinen passenden slot für itemdId %s finden"
  rggm.L["unable_to_find_item"] = "Konnte keine Iteminformationen für itemId %s finden"
  rggm.L["macro_invalid_argument"] = "Ungültiges Argument #%s an '%s' (Zahl erwartet, %s erhalten)"
  rggm.L["macro_invalid_listener"] = "Ungültiges Argument #1 an '%s' (Funktion erwartet, %s erhalten)"

  -- swap failure user errors
  rggm.L["swap_failure_item_not_found"] = "Konnte nicht zu Gegenstand %s wechseln - der Gegenstand wurde nicht "
    .. "in den Taschen gefunden"
  rggm.L["swap_failure_item_locked"] = "Konnte nicht zu Gegenstand %s wechseln - der Gegenstand ist gerade gesperrt"
  rggm.L["swap_failure_cursor_busy"] = "Konnte nicht zu Gegenstand %s wechseln - ein anderer Gegenstand befindet "
    .. "sich am Cursor"
  rggm.L["swap_failure_spell_targeting"] = "Konnte nicht zu Gegenstand %s wechseln - ein Zauber wartet auf ein Ziel"
  rggm.L["swap_failure_no_bag_space"] = "Konnte Gegenstand %s nicht ablegen - kein freier Platz in den Taschen"
  rggm.L["swap_fallback_to_base_item"] = "Ersatzkopie von %s ausgerüstet - keine Kopie mit der exakten"
    .. " Verzauberung/Rune in den Taschen gefunden"

  -- profile
  rggm.L["profile_category_name"] = "Profile"
  rggm.L["profile_title"] = "Konfigurationsprofile"
  rggm.L["profile_list_label"] = "Gespeicherte Profile"
  rggm.L["profile_string_label"] = "Profilzeichenkette (Export / Import)"
  rggm.L["profile_save_button"] = "Aktuelles speichern als..."
  rggm.L["profile_apply_button"] = "Anwenden"
  rggm.L["profile_rename_button"] = "Umbenennen"
  rggm.L["profile_delete_button"] = "Löschen"
  rggm.L["profile_export_button"] = "Exportieren"
  rggm.L["profile_import_button"] = "Importieren"
  rggm.L["profile_name_prompt"] = "Gib einen Namen für das neue Profil ein:"
  rggm.L["profile_rename_prompt"] = "Gib einen neuen Namen für das Profil ein:"
  rggm.L["profile_import_name_prompt"] = "Gib einen Namen ein, unter dem das importierte Profil gespeichert wird:"
  rggm.L["profile_apply_confirm"] = "Profil \"%s\" anwenden? Dies überschreibt deine aktuellen Einstellungen "
    .. "und lädt die Benutzeroberfläche neu."
  rggm.L["profile_delete_confirm"] = "Profil \"%s\" löschen?"
  rggm.L["profile_save_success"] = "Profil \"%s\" gespeichert"
  rggm.L["profile_apply_success"] = "Profil \"%s\" angewendet"
  rggm.L["profile_import_success"] = "Profil \"%s\" importiert"
  rggm.L["profile_delete_success"] = "Profil \"%s\" gelöscht"
  rggm.L["profile_rename_success"] = "Profil umbenannt in \"%s\""
  rggm.L["profile_error_empty"] = "Es gibt keine Profilzeichenkette zum Importieren"
  rggm.L["profile_error_invalid"] = "Die Profilzeichenkette ist ungültig oder konnte nicht gelesen werden"
  rggm.L["profile_error_checksum"] = "Die Profilzeichenkette ist beschädigt (Prüfsummenfehler)"
  rggm.L["profile_error_wrong_addon"] = "Diese Profilzeichenkette wurde nicht von GearMenu erstellt"
  rggm.L["profile_error_version"] = "Diese Profilzeichenkette wurde von einer neueren Version von GearMenu erstellt"
  rggm.L["profile_error_name_empty"] = "Der Profilname darf nicht leer sein"
  rggm.L["profile_error_name_exists"] = "Ein Profil mit diesem Namen existiert bereits"
  rggm.L["profile_error_no_selection"] = "Kein Profil ausgewählt"
end
