on: [workflow_dispatch]

jobs:
  curseforge-release-job:
    runs-on: ubuntu-latest
    name: CurseForge Release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Package Production
        run: mvn generate-resources -D generate.sources.overwrite=true -P release
      - name: Publish Package to CurseForge
        run: mvn package -P deploy-curseforge-action -D curseforge.auth-token=$TOKEN_CURSEFORGE
        env:
          TOKEN_CURSEFORGE: ${{ secrets.TOKEN_CURSEFORGE }}
